title: Choi-Jiwon-38's Blog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://choi-jiwon-38.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: Choi-Jiwon-38
  instagram: aid_choi
  facebook: choijw9837
  email: qwerty_02@kookmin.ac.kr

google_analytics: "G-K6EWZWNW9J"

comment:
  provider: "disqus"
  disqus:
    shortname: "Choi-Jiwon-38"